#!/bin/bash

echo -n "Enter the name of an animal: "
read ANIMAL
echo -n "The $ANIMAL has "
case $ANIMAL in
  horse | dog | cat | donkey) echo -n "four";;
  woman | man | kangaroo | chicken) echo -n "two";;
  *) echo -n "an unknown number of";;
esac
echo " legs."
