#!/bin/bash

for koko in 1 2 3 4 5
do
  echo $koko 
#Ektypwsh se diaforetikes grammes
done

for koko in "1 2 3 4 5"
do
  echo $koko 
#Ektypwsh se mia grammh
done

NUMS="1 2 3 4 5"
for koko in $NUMS
do
  echo $koko 
#Ektypwsh se diaforetikes grammes
done

for koko in `echo $NUMS`
do
  echo $koko 
#Ektypwsh se diaforetikes grammes
done

LIMIT=8
#Diples parentheseis, LIMIT xwris $
for ((koko=1; koko <= LIMIT; koko++)) 
do
  echo $koko "loop me limit"
#Ektypwsh se diaforetikes grammes
done

