#!/bin/sh
#search for .h files in a specific directory
#For each file in this dir, list first 3 lines in the file
#into the file "myout"

FILE_LIST=`ls /usr/include/c++/5/parallel/*.h`

touch myout; rm myout; touch myout;

for file in ${FILE_LIST}
  do
  echo FILE = ${file}
      head -3 "${file}" >> myout
  done

