#!/bin/bash    

# PROSOXH: APAITOYNTAI KENA
a=`expr 3 + 5`; echo $a      # 8           
a=`expr 5 % 3`; echo $a      # 2           
a=`expr 5 / 3`; echo $a      # 1           
#a=`expr 1 / 0` # Epistrefei sfalma           
a=`expr 5 \* 3`; echo $a     # 15           
# Me to expr, ston pollaplasiasmo \* 

a=`expr $a + 5`; echo $a # Idio me let a=a+5           

string=EnaMegaloString
echo "String is: ${string}"
position=4
length=6
z=`expr substr $string $position $length`
#E3agei length xarakthres apo to string.
#3ekinaei apo th 8esh position

echo "Sunstring is: $z"  # Megalo
