#!/bin/bash

echo Input parameters = $#
myvar="one two three four five six"

#split based on blank chars
#assign to input parameters!!
set -- $myvar

echo Input parameters = $#
#Now prints 6

for koko 
do
  echo $koko 
done

