#!/bin/bash
# call with > 5 arguments

echo "All args are = $*"
for str  # prints OK even with change
 	do
	echo "The value of the iterator is: ${str} "
	var=$1
	shift
	echo "var = $var and args = $*"
	done
